# No fancyness - we can use the new build infrastructure
sudo: false

language:
  - java

jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov

script:
  - mvn integration-test

after_success:
  - codecov

deploy:
  # deploy master to OSSHR Snapshot
  - provider: script
    script: mvn deploy
    on:
      branch: master
